#!/usr/bin/env bash
set -ex

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH
mkdir $GOPATH/bin

cd $GOPATH/src/github.com/williammartin/nsjam
ginkgo -tags daemon -r -p -race -cover -keepGoing -nodes=1 "$@"
