#!/usr/bin/env bash

set -e

ARGS=$@

DIRS=$(for d in $ARGS; do [ -d "$d" ] && echo "$d"; done)

if egrep -q marley <(echo "$ARGS"); then
   (./scripts/remote-fly ci/marley.yml -- $ARGS)
else
  ginkgo -race $ARGS
fi
